version: '3'

services:
   db: 
      build: ./db
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      networks:
         - core
         
   apparel:
      build: ./apparel
      volumes:
         - ./apparel:/app
      depends_on:
         - db
      ports:
         - 5001:80
      networks:
         - core
         
   prices:
      build: ./prices
      volumes:
         - ./prices:/app
      depends_on:
         - apparel
      ports:
         - 5002:80
      networks: 
         - core
         - site
         
   site:
      build: ./site
      volumes:
         - ./site:/src
      depends_on:
         - prices
      ports:
         - 5000:80
      networks:
         - site
         
networks:
  core:
     driver: bridge
  site:
     driver: bridge
      

